/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myfiltercamera_MainActivity */

#ifndef _Included_com_example_myfiltercamera_MainActivity
#define _Included_com_example_myfiltercamera_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_myfiltercamera_MainActivity_VIEW_MODE_RGBA
#define com_example_myfiltercamera_MainActivity_VIEW_MODE_RGBA 0L
#undef com_example_myfiltercamera_MainActivity_VIEW_MODE_BLUR
#define com_example_myfiltercamera_MainActivity_VIEW_MODE_BLUR 1L
#undef com_example_myfiltercamera_MainActivity_VIEW_MODE_SEPIA
#define com_example_myfiltercamera_MainActivity_VIEW_MODE_SEPIA 2L
#undef com_example_myfiltercamera_MainActivity_VIEW_MODE_POSTERIZE
#define com_example_myfiltercamera_MainActivity_VIEW_MODE_POSTERIZE 3L
#undef com_example_myfiltercamera_MainActivity_VIEW_MODE_PIXELIZE
#define com_example_myfiltercamera_MainActivity_VIEW_MODE_PIXELIZE 4L
#undef com_example_myfiltercamera_MainActivity_VIEW_MODE_NEGATIVE
#define com_example_myfiltercamera_MainActivity_VIEW_MODE_NEGATIVE 5L
#undef com_example_myfiltercamera_MainActivity_VIEW_MODE_CANNY
#define com_example_myfiltercamera_MainActivity_VIEW_MODE_CANNY 6L
#undef com_example_myfiltercamera_MainActivity_VIEW_MODE_SOBEL
#define com_example_myfiltercamera_MainActivity_VIEW_MODE_SOBEL 7L
#undef com_example_myfiltercamera_MainActivity_VIEWM_MODE_BACKGROUND
#define com_example_myfiltercamera_MainActivity_VIEWM_MODE_BACKGROUND 8L
/*
 * Class:     com_example_myfiltercamera_MainActivity
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_myfiltercamera_MainActivity_loadCascade
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_myfiltercamera_MainActivity
 * Method:    detect
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_myfiltercamera_MainActivity_detect
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
